#!/bin/bash 
set -eou pipefail

. ./utils.sh

announce "Rotating password."

set_project $CONJUR_PROJECT_NAME

conjur_master=$(get_master_pod_name)
new_pwd=$(openssl rand -hex 12)

oc exec $conjur_master -- conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD
oc exec $conjur_master -- conjur variable values add test-app-db/password $new_pwd
oc exec $conjur_master -- conjur authn logout

echo "New db password is:" $new_pwd
