#!/bin/bash 
set -eou pipefail

. ./utils.sh

oc project default

if has_project $TEST_APP_PROJECT_NAME; then
  oc delete project $TEST_APP_PROJECT_NAME

  printf "Waiting for $TEST_APP_PROJECT_NAME project deletion to complete"

  while : ; do
    printf "..."
    
    if has_project "$TEST_APP_PROJECT_NAME"; then
      sleep 5
    else
      break
    fi
  done

  echo ""
fi

echo "Test app environment purged."

if [ -d openshift-conjur-deploy ]; then
  pushd openshift-conjur-deploy
    ./stop
  popd

  rm -rf ./openshift-conjur-deploy
fi
